name: Build and deploy chrome extension

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'    

jobs:
  build:
    name: Build chrome extension
    runs-on: ubuntu-latest    
    
    steps:      
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build project
      run: npm run build:prod
    
    - name: Zip contents
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r extension.zip dist

    - name: Install dependencies for upload script
      run: npm install node-fetch@2.6.6
    
    - name: Upload and publish to Chrome Web Store
      run: node ./scripts/upload.js
      env:
        CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
        CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
        APP_ID: ${{ secrets.CHROME_APP_ID }}
